# general configuration 

module: "end-to-end"
workdir : "."
basedir: ""
outdir : "results/"
datadir : "fastq/"
samplelist : ""
fasta: ""
fastadir: ""
sample-name: ""
assembly-ids: ""
latest-run : ""
splits: 0
keep-intermediates: False
setup-database: True
max-cores: 4
NCBI-email: "vomixtest@gmail.com"
NCBI-API-key: ""

# setup-database.smk

hostile-index-db: "database/hostile"
PhaBox2-db: "database/phabox_db_v2"
genomad-db: "database/genomad"
virsorter2-db: "database/virsorter2"
vibrant-db: "database/vibrant"
checkv-db: "database/checkv"
iphop-db: "database/iphop"
iphop-db-version: "iPHoP_db_Aug23_rw"
iphop-db-basename: "Aug_2023_pub_rw" # make sure base name is compatible with version https://bitbucket.org/srouxjgi/iphop/src/main/#markdown-header-host-databases-and-versions
eggNOG-db: "database/eggNOGv2"
eggNOG-db-params: ""
humann-db: "database/humann"
checkm2-db: "database/checkm2"
GTDBTk-db: "database/GTDB-Tk"
GTDBTk-db-version: "220" # Make sure that the database is compatible with the version of GTDB-Tk used https://ecogenomics.github.io/GTDBTk/installing/index.html#gtdb-tk-reference-data in the current vomix


# preprocess.smk

dwnld-params : ""
dwnld-only: False
pigz-params: ""
fastp-params: ""
decontam-host: True
hostile-params: ""
hostile-index-name: "human-t2t-hla" # visit https://github.com/bede/hostile to find out how to make your own custom host index or see other available indexes.
hostile-aligner: "bowtie2" # minimap2 for long reads or bowtie2 for short reads
hostile-aligner-params: "" # parameters to pass to aligner

# assembly.smk 

assembler: "megahit" #["megahit", "spades"]
megahit-min-len: 300
megahit-params: "--prune-level 3"
spades-params: "--meta"
spades-memory: 250


# viral-identify.smk viral-benchmark.smk

contig-min-len: 0
genomad-min-len: 1000
genomad-params: "--enable-score-calibration --relaxed"
genomad-cutoff: 0.7
genomad-cutoff-s: 0


# viral-identify.smk viral-benchmark.smk & checkv-pyhmmer.smk

checkv-original: False
checkv-params: ""


# viral-identify.smk viral-benchmark.smk & clustering.smk

clustering-fast: True
cdhit-params: "-c 0.95 -aS 0.85 -d 400 -M 0 -n 5"
vOTU-ani: 95
vOTU-targetcov: 85
vOTU-querycov: 0


# viral-benchmark.smk

dvf-min-len: 1500
phamer-min-len: 2000 

dvf-params: ""
phamer-params: ""
virsorter2-params: ""
vf-params: ""
vibrant-params: ""
seeker-params: ""
ppr-params: ""

dvf-cutoff: 0.7
dvf-pval: 0.05
phamer-cutoff: 0.7
phamer-pred: "phage"
vf-cutoff: 0
virsorter2-cutoff: 0
seeker-cutoff: 0
ppr-cutoff: 0
vibrant-cutoff: 0


# viral-taxonomy.smk

phagcn-min-len: 1000 # the minimum tested
phagcn-params: ""
genomad-params-tax: "--enable-score-calibration --relaxed"


# viral-community.smk

coverm-params: "--mapper minimap2-sr --min-read-percent-identity 95 --min-read-aligned-percent 75 --trim-min 10 --trim-max 90" # checkout coverm documentation for options https://wwood.github.io/CoverM/coverm-make.html
coverm-methods : "tpm rpkm" # a space delimited list from coverm options


# viral-host.smk

iphop-host: False
iphop-cutoff: 90
iphop-params: ""
CHERRY-params: ""
PhaTYP-params: ""


# viral-annotate.smk

eggNOG-params: "-m diamond --hmm_evalue 0.001 --hmm_score 60 --query-cover 20 --subject-cover 20 --tax_scope auto --target_orthologs all --go_evidence non-electronic --report_orthologs"
PhaVIP-params: ""

# prok-community.smk

mpa-params: "--ignore_eukaryotes"
mpa-indexv: "mpa_vOct22_CHOCOPhlAnSGB_202212"


# prok-binning.smk 

binning-consensus: False
strobealign-params: ""
MetaBAT2-params: "-m 1500"
MaxBin2-params: "-min_contig_length 1500 -max_iteration 50 -prob_threshold 0.9"
CONCOCT-params: ""
jgi-summarize-params: "--percentIdentity 97"
DASTool-params: ""
checkm2-params: ""
drep-params: ""
galah-params: "--ani 95 --min-aligned-fraction 15 --fragment-length 3000"
GTDBTk-identify-params: ""
GTDBTk-align-params: ""
GTDBTk-classify-params: ""
VAMB-params: "-m 100"


# prok-annotate.smk
humann-params: ""

